# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/haberdasher.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsrc/proto/haberdasher.proto\"\x16\n\x04Size\x12\x0e\n\x06inches\x18\x01 \x01(\x05\"2\n\x03Hat\x12\x0e\n\x06inches\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2%\n\x0bHaberdasher\x12\x16\n\x07MakeHat\x12\x05.Size\x1a\x04.Hatb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.haberdasher_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIZE._serialized_start=31
  _SIZE._serialized_end=53
  _HAT._serialized_start=55
  _HAT._serialized_end=105
  _HABERDASHER._serialized_start=107
  _HABERDASHER._serialized_end=144
# @@protoc_insertion_point(module_scope)
